### ISSUE TITLE
ID5 Task list - to keep track of all the remaining tasks

### ISSUE THREAD

**Issue by nisarg-11-here** [UniversityOfSaskatchewanCMPT371/term-project-2024-team-4#104]
For ID5 the main focus is to clean the code, branches, and merge all the features together. 

Implement the features that are still left and add more functionality to the ones that are implemented:

- [x] Admin privileges check - Check if only admins are able to use the Creation of site, creation of projectile point, data management, export, and import functionality. Users without logging in should not be able to use these features. 
- [x] Adding and Modifying Sites and Projectile Points
- [x] Edit the site added to the catalogue - Admins should be able to edit the details about a site that is already added. 
- [x] Edit the projectile point details which is added to the catalogue - Admins should be able to edit the details of any projectile point that already exists.
- [x] Deletion of a site
- [x] Deletion of a projectile point
- [x] Aggregated Statistics - Check the trueness of the statistics generated and add pie charts to it. 
- [x] Data management Page - Admins should be able to create or delete, period, cultures or materials to be used while creation of actual projectile points to make it easier for them to create new projectile points. 
- [x] Settings - Username and Password change option - should open up a modal which allows admins to change the admin username and password. This should check If the user is logged in first.
- [ ] Export in JSON - For the import functionality
   - [ ] Problem: The cascaded data can be challenging to be exported.
- [ ] Import (Using the JSON file which is exported) - Creates a new catalogue (give more thoughts to this) - maybe on the import page, should display all the imported catalogues - should just contain all the projectile points without the need to sort them by sites. 
   - [ ] Problem: In the database, I am not sure if each site and projectile point is linked to the catalogue using a catalogueID, if not then added new data to the database using import can cause data redundancy and data loss. 

Please refer to the requirements document for detailed description about any feature or ask PM.
