### ISSUE TITLE
Test Team To-do lists for ID1

### ISSUE THREAD

**Issue by m-jewel** [UniversityOfSaskatchewanCMPT371/term-project-2024-team-4#7]
- [x] @Jorden Whitenect  research more about automated unit testing. I know it is the dev team job to do but we can help them in some way to make the process easier
- [x] @John L.  research more about the CI pipeline that we will use and how we can do it using GitHub actions
- [x] @Kelly  research better logging and mocking mechanism
- [x] @m.jewel  GUI testing for REACTJS and finalize what automated smoke testing we will do 
- [x] @Adam S I know you're busy with making the design but I still would like you to also work with Jewel for the best smoke testing mechanisms.
